services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
 
  hasura:
    image: hasura/graphql-engine:v2.36.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL : postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      # HASURA_GRAPHQL_DEV_MODE : "true"
      # HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      # HASURA_GRAPHQL_JWT_SECRET: '{
      #   "type": "HS256",
      #   "key" : "https://openam-informa-trial.forgeblocks.com:443/am/oauth2/bravo/connect/jwk_uri",
      #   "claims_namespace": "https://hasura.io/jwt/claims"
      # }'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecret
    volumes:
        - ./hasura/metadata:/hasura-metadata
        - ./hasura/migrations:/hasura-migrations
        # - ./hasura/seeds:/hasura-seeds
        
volumes:
  pg_data: