name: Track Hasura Metadata

on: push
#resolved
jobs:
  track-metadata:
    runs-on: self-hosted
    steps:
      # - name: Clone repo manually
      #   run: |
      #     echo "clonning repo..."
      #     git clone https://github.com/shubhaminforma/hasura-metadata-tracking.git
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: test 1
      #   run: |
      #     if true; then
      #       echo "No metadata changes to commit."
      #     else
      #       echo "succ
      #     fi
      
      - name: test 2
        if: true
        run: echo ":succes 2"


      - name: Export Hasura metadata
        run: |
          cd hasura-project
          echo "Exporting Hasura metadata..."
          hasura metadata export

      # - name: Commit and push metadata changes
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"

      #     git add metadata/
      #     if (git diff --cached --quiet); then
      #       echo "No metadata changes to commit."
      #     else
      #       git commit -m "Auto-export Hasura metadata on push"
      #       git push origin HEAD
      #     fi
