name: Track Hasura Metadata

on: push

jobs:
  track-metadata:
    runs-on: self-hosted
    #resolved
    steps:
      - name: Clone repo manually
        run: |
          git clone https://github.com/shubhaminforma/hasura-metadata-tracking.git


      - name: Export Hasura metadata
        run: |
          echo "Exporting Hasura metadata..."
          hasura metadata export

      - name: Commit and push metadata changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add metadata/
          if git diff --cached --quiet; then
            echo "No metadata changes to commit."
          else
            git commit -m "Auto-export Hasura metadata on push"
            git push origin HEAD
          fi
